# Generated by Django 4.1.3 on 2022-11-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_chatmessage_chatroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
